### ISSUE TITLE
getting error while training on CPU

### ISSUE THREAD

**Issue by lalitkishorevyas** [cesc-park/attend2u#15]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lalit/notebooks/Lalit/image_caption/attend2u/train.py", line 211, in <module>
    tf.app.run()
  File "/home/lalit/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/lalit/notebooks/Lalit/image_caption/attend2u/train.py", line 208, in main
    train()
  File "/home/lalit/notebooks/Lalit/image_caption/attend2u/train.py", line 134, in train
    loss = _tower_loss(inputs, scope)
  File "/home/lalit/notebooks/Lalit/image_caption/attend2u/train.py", line 33, in _tower_loss
    net = CSMN(inputs, ModelConfig(FLAGS))
  File "utils/configuration.py", line 33, in __init__
    super(ModelConfig, self).__init__(FLAGS)
  File "utils/configuration.py", line 12, in __init__
    attrs = FLAGS.__dict__['__flags']
KeyError: '__flags'

**Comment by dhruv2601** [comment]
Syntax has changed since 1.4, you can use the following code below -

`    def __init__(self, FLAGS): 
        attrs = FLAGS.flag_values_dict()  
        for attr in attrs:
            setattr(self, attr.lower(), getattr(FLAGS, attr))`
